CREATE DATABASE ungdung_quanly_furama;
USE ungdung_quanly_furama;
CREATE TABLE kieuthue(
IDKieuThue INT AUTO_INCREMENT PRIMARY KEY,
TenKieuThue VARCHAR(45),
Gia INT
);
CREATE TABLE loaidichvu(
IDLoaiDichVu INT AUTO_INCREMENT PRIMARY KEY,
TenLoaiDichVu VARCHAR(45)
);
CREATE TABLE dichvu(
IDDichVu INT AUTO_INCREMENT PRIMARY KEY,
TenDichVu VARCHAR(45),
DienTich INT,
SoTang INT,
SoNguoiToiDa INT,
ChiPhiThue DOUBLE,
IDKieuThue INT,
IDLoaiDichVu INT,
TrangThai VARCHAR(45),
FOREIGN KEY (IDKieuThue) REFERENCES kieuthue (IDKieuThue),
FOREIGN KEY (IDLoaiDichVu) REFERENCES loaidichvu (IDLoaiDichVu)
);
CREATE TABLE vitri(
IDViTri INT AUTO_INCREMENT PRIMARY KEY,
TenViTri VARCHAR(45)
);
CREATE TABLE trinhdo(
IDTrinhDo INT AUTO_INCREMENT PRIMARY KEY,
TrinhDo VARCHAR(45)
);
CREATE TABLE bophan(
IDBoPhan INT AUTO_INCREMENT PRIMARY KEY,
TenBoPhan VARCHAR(45)
);
CREATE TABLE nhanvien(
IDNhanVien INT AUTO_INCREMENT PRIMARY KEY,
HoTen VARCHAR(45),
IDViTri INT,
IDTrinhDo INT,
IDBoPhan INT,
NgaySinh DATE,
SoCMND INT,
Luong DOUBLE,
SDT INT,
Email VARCHAR(45),
DiaChi VARCHAR(45),
FOREIGN KEY (IDViTri) REFERENCES vitri(IDViTri),
FOREIGN KEY (IDTrinhDo) REFERENCES trinhdo(IDTrinhDo),
FOREIGN KEY (IDBoPhan) REFERENCES bophan(IDBoPhan)
);
CREATE TABLE loaikhach(
IDLoaiKhach INT AUTO_INCREMENT PRIMARY KEY,
TenLoaiKhach VARCHAR(45)
);
CREATE TABLE khachhang(
IDKhachHang INT AUTO_INCREMENT PRIMARY KEY,
IDLoaiKhach INT,
HoTen VARCHAR(45),
NgaySinh DATE,
SoCMND INT,
SDT INT,
Email VARCHAR(45),
DiaChi VARCHAR(45),
FOREIGN KEY (IDLoaiKhach) REFERENCES loaikhach(IDLoaiKhach)
);
CREATE TABLE hopdong(
IDHopDong INT AUTO_INCREMENT PRIMARY KEY,
IDNhanVien INT,
IDKhachHang INT,
IDDichVu INT,
NgayLamHopDong DATE,
NgayKetThuc DATE,
TienDatCoc DOUBLE,
TongTien DOUBLE,
FOREIGN KEY (IDNhanVien) REFERENCES nhanvien(IDNhanVien),
FOREIGN KEY (IDKhachHang) REFERENCES khachhang(IDKhachHang),
FOREIGN KEY (IDDichVu) REFERENCES dichvu(IDDichVu)
);
CREATE TABLE dichvudikem(
IDDichVuDiKem INT AUTO_INCREMENT PRIMARY KEY,
TenDichVuDiKem VARCHAR(45),
Gia INT,
DonVi INT,
TrangThaiKhaDung VARCHAR(45)
);
CREATE TABLE hopdongchitiet(
IDHopDongChiTiet INT AUTO_INCREMENT PRIMARY KEY,
IDHopDong INT,
IDDichVuDiKem INT,
SoLuong INT,
FOREIGN KEY (IDHopDong) REFERENCES hopdong(IDHopDong),
FOREIGN KEY (IDDichVuDiKem) REFERENCES dichvudikem(IDDichVuDiKem)
);